### ISSUE TITLE
How to pause and resume the upload process in Android

### ISSUE THREAD

**Issue by kanagalingam** [cloudinary/cloudinary_java#102]
Hi,
Can we have some code to pause and download the upload process for urlconnection in Android

**Comment by MaorGariv** [comment]
Hi @kanagalingam,

Thanks for reaching out.

**Exciting news!**

 Cloudinary Android SDK just received a major upgrade!

Some of the newly supported features - 

 **Network**

 * Upload on wifi only ("unmetered")
 * Upload on wifi and cellular ("metered") networks

**Charging**

 * Upload only when charging
 * Upload anytime
 * Upload only when the device is idle

**Resume upload**

 * Maximum retries before failing the request permanently

You can find the repo with many basic and advanced samples [here](https://github.com/cloudinary/cloudinary_android)

Let me know how it goes:)

**Comment by MaorGariv** [comment]
Hey,

Pausing, resuming and other upload management options are supported in our new Android SDK release:)

I'm setting this request as solved. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Comment by yakirp** [comment]
Hi @redrose218 ,

I'm sorry, but our Android SDK does not support this functionality, you can stop (=cancel) but not pause or resume manually.
It does get paused and resumed automatically when the network goes down though.

Thanks
--Yakir
