### ISSUE TITLE
Thymeleaf support

### ISSUE THREAD

**Issue by JelleBlaauw** [cloudinary/cloudinary_java#103]
Will you guys add support for Thymeleaf?

**Comment by idobarnoam** [comment]
Hi @JelleBlaauw,

We currently don't have an SDK for Thymeleaf. There is also no current plan to support it at the present moment. Note that this might change in the future as we aim to support many popular frameworks.

Please let me know if you have any additional questions.

**Comment by JelleBlaauw** [comment]
That's a shame. If I'm correct, Thymeleaf is being used a lot these days, and growing in popularity swiftly. Definitely worth checking it out. 

I look forward to hearing about future developments. Thanks you for your time.

**Comment by idobarnoam** [comment]
Thank you for the input.

You can follow us on our [FB community](https://www.facebook.com/groups/CloudinaryCommunity/) to hear about our newest features.

I will close this thread now, but please feel free to open it if you think there is a need to.
