### ISSUE TITLE
Please deprecate the cloudinary-android folder

### ISSUE THREAD

**Issue by louistsaitszho** [cloudinary/cloudinary_java#109]
The [cloudinary website](http://cloudinary.com/documentation) takes me to this cloudinary-andorid folder when this is no longer in use. Please
1) either remove that folder or write in big letter in the README that that documentation has been deprecated
2) change the cloudinary website href to the right repo

Thanks!

**Comment by roeeba** [comment]
Hi @louistsaitszho, thank you very much for pointing it out. We'll make sure to fix this as soon as we can.

**Comment by roeeba** [comment]
Hi @louistsaitszho. Issue resolved - folder was removed. 
Thank you again.
