### ISSUE TITLE
unable to generate video url and video thumbnail url

### ISSUE THREAD

**Issue by krzaq464** [cloudinary/cloudinary_java#112]
Hi, I'm trying to generate an url and thumbnail for a video uploaded to cloudinary. I tried many different ways to do it but without luck.
1. This method:
cld.url().cloudName(cloudName).posterSource(publicId).transformation(new Transformation()).generate(publicId);
results in http://res.cloudinary.com/some-cloud/image/upload/v1_duemao.png whicj is incorrect.
2. This approach 
cld.url().cloudName(cloudName).fromIdentifier(publicId).generate()
results in the same as above.

What I'd like to achieve is:
http://res.cloudinary.com/some-cloud/video/upload/v1_duemao.jpg

How to do that? Is it supported at all?
Thanks in advance.

**Comment by d-mendoza** [comment]
Hi @krzaq464,

I would like to apologize for the delay.

You can try the following:
`cld.url().cloudName(cloudName).resourceType("video").publicId(pId).format("jpg").generate()` 
That will generate this URL: `http://res.cloudinary.com/some-cloud/video/upload/some-pId.jpg`

Please let me know if this works for you.

**Comment by d-mendoza** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
