### ISSUE TITLE
Allow customization of HttpClient(Builder)

### ISSUE THREAD

**Issue by ceefour** [cloudinary/cloudinary_java#115]
For example, we'd like to [use AWS X-Ray to trace outgoing HTTP calls](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-httpclients.html). 

https://github.com/cloudinary/cloudinary_java/blob/a3612ab6e29ce01748985bacc6cd6d9977a90f23/cloudinary-http44/src/main/java/com/cloudinary/http44/UploaderStrategy.java#L40-L54

For the AWS X-Ray use case, it should be possible to provide a custom `HttpClientBuilder` instance, which will be used instead of the hardcoded `HttpClients.custom()`.

**Comment by roeeba** [comment]
HI @ceefour. Currently, you can only customize `HttpClientConnectionManager`. I've forward your request to our dev team to review. We will update here if and when this will be implemented.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
