### ISSUE TITLE
Metadata from uploaded Images

### ISSUE THREAD

**Issue by azngeek** [cloudinary/cloudinary_java#124]
Is there a way to get the information of uploaded images? I would like to store that meta data somewhere but need to retreive it from the API.

**Comment by roeeba** [comment]
Hi @azngeek, you can use the [Admin API](https://cloudinary.com/documentation/admin_api#details_of_a_single_resource) to extract a resource's metadata (by setting `image_metadata` to true).

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
