### ISSUE TITLE
Java generic raw types are not supported in Kotlin and thus the Android lib is not compatible with kotlin

### ISSUE THREAD

**Issue by kayvannj** [cloudinary/cloudinary_java#131]
https://github.com/cloudinary/cloudinary_java/blob/d4e157401fe0a0317496a6a179b7b24b677dafd6/cloudinary-core/src/main/java/com/cloudinary/Transformation.java#L15

**Comment by kayvannj** [comment]
Hi, 
In this issue, I'm pointing to Java language Raw types http://www.javapractices.com/topic/TopicAction.do?Id=224 and not the media format.

**Comment by aditimadan-Cloudinary** [comment]
Sure. Will suggest our document team to add this.

Thanks,
Aditi

**Comment by hazzyeer** [comment]
A beta version : https://cloudinary.com/documentation/kotlin_integration
