### ISSUE TITLE
Missing Singleton Class in com.cloudinary.Singleton

### ISSUE THREAD

**Issue by BYH535** [cloudinary/cloudinary_java#145]
Hi, I am using the cloudinary API version 1.0.14 and I have created a class exactly like [cloudinary_java/samples/photo_album/src/main/java/cloudinary/models/PhotoUpload.java](https://github.com/cloudinary/cloudinary_java/blob/master/samples/photo_album/src/main/java/cloudinary/models/PhotoUpload.java) but I have got this error :
![untitled](https://user-images.githubusercontent.com/39955400/45230235-2809dc80-b2c0-11e8-86fa-51cff953065c.png)

**Comment by aditimadan-Cloudinary** [comment]
Can you please share your pom.xml and did you try with the latest version 1.19.0?

**Comment by BYH535** [comment]
The error comes when I try to work with 
`<dependency>
            <groupId>com.cloudinary</groupId>
            <artifactId>cloudinary</artifactId>
            <version>1.0.14</version>
</dependency>`
, but when using 
![image](https://user-images.githubusercontent.com/39955400/45286252-3a149680-b4dd-11e8-925b-85208440ef93.png), the error is gone

**Comment by aditimadan-Cloudinary** [comment]
Singleton class is part of the taglib library. Make sure to add the cloudinary-taglib to your pom and it will work. It is always recommended to use the latest version.
<dependency>
            <groupId>com.cloudinary</groupId>
            <artifactId>cloudinary-taglib</artifactId>
            <version>1.0.14</version>
   </dependency>
