### ISSUE TITLE
Configuration for windows

### ISSUE THREAD

**Issue by vireshmanagooli** [cloudinary/cloudinary_java#16]
Can please someone guide me how the set up the following in windows environment? I have been struggling to run sample program in windows environment.  

https://github.com/cloudinary/cloudinary_java/tree/master/samples/photo_album#configuration

Thanks in advance.

**Comment by tocker** [comment]
Hi @vireshmanagooli,

Did you set the `TOMCAT_OPTS` environment variable as suggested in the documentation?

See [here](http://www.nextofwindows.com/how-to-addedit-environment-variables-in-windows-7/) for detailed instructions on setting environment variables in windows.

**Comment by tocker** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support [http://support.cloudinary.com](http://support.cloudinary.com) or create a new ticket if you have any additional issues.
