### ISSUE TITLE
Cloudinary maven dependencies are not getting resolved

### ISSUE THREAD

**Issue by abhishukl** [cloudinary/cloudinary_java#192]
Hi Cloudinary Team,

I am evaluating Cloudinary to replace S7, while doing initial hands-on, encountered maven dependency resolution issue. I am at trying to use cloudinary java with AEM6.3 version.

Below is the maven dependency:
<dependency>
	            <groupId>com.cloudinary</groupId>
	            <artifactId>cloudinary-taglib</artifactId>
	            <version>1.23.0</version>
	        </dependency>
	         <dependency>
	            <groupId>com.cloudinary</groupId>
	            <artifactId>cloudinary-http44</artifactId>
	            <version>1.23.0</version>
	        </dependency>

While using com.cloudinary.Cloudinary, com.cloudinary.utils.ObjectUtils libraries, my AEM bundle is not resolving at runtime.
 Below is the error, at AEM felix console.
com.cloudinary -- Cannot be resolved
com.cloudinary.utils -- Cannot be resolved

due to which I am not able to execute my Workflow which is to upload assets from AEM DAM to Cloudinary.

Please help.

Regards,
Abhishek

**Comment by aditimadan-Cloudinary** [comment]
Hi Abhishek,

Which java version are you using? Can you please share the maven dependency file?

Thanks,
Aditi
