### ISSUE TITLE
Do you really support images/videos bulk upload?

### ISSUE THREAD

**Issue by lombocska** [cloudinary/cloudinary_java#197]
Hey guys,

it's just a quick and short question.

I read your documentation about java integration, especially the [`Preview thumbnail, progress indication, multiple images`](https://cloudinary.com/documentation/java_image_upload) part, multiple times. 

So, maybe, it's just me, but I don't really get how the below mentioned code part will upload images/videos in bulk? Or am I missing something?
Because the single upload `cloudinary.uploader().upload(file, params)`  is quite obvious, but the bulk is not (for me).

```
Map options = ObjectUtils.emptyMap();
Map htmlOptions = ObjectUtils.asMap("multiple", true);
String html = cloudinary.uploader().imageUploadTag("image_id", options, htmlOptions);
```

Thanks in advance.
Moni

**Comment by michalkcloudinay** [comment]
Hi @lombocska, This is used if you have a web app that allows your users to upload images from browsers using JQuery. The image data is first sent to your server to generate the tags with java and only then uploaded to Cloudinary.
