### ISSUE TITLE
Android library: Upload Raw files. 

### ISSUE THREAD

**Issue by coomar2841** [cloudinary/cloudinary_java#20]
How do I upload a raw file to cloudinary using the android SDK? If I use the upload method, which works for images, it saves the file as an image(for a video). 

I tried the uploadLargeRaw method, but getting errors.

<pre>
java.lang.RuntimeException: Missing required parameter - file
at com.cloudinary.android.UploaderStrategy.callApi(UploaderStrategy.java:101)
at com.cloudinary.Uploader.callApi(Uploader.java:22)
at com.cloudinary.Uploader.uploadLargeRawParts(Uploader.java:116)
at com.cloudinary.Uploader.uploadLargeRaw(Uploader.java:75)
at com.cloudinary.Uploader.uploadLargeRaw(Uploader.java:59)
</pre>

**Comment by tocker** [comment]
Based on your error stack, it looks like you are using older code. Please refresh your code (version as of writing is [1.2.0](http://mvnrepository.com/artifact/com.cloudinary/cloudinary-android/1.2.0)), and try again.

If you are still experiencing this error, please include the relevant segment of your code together with the error stack.

**Comment by coomar2841** [comment]
Ok, I tried 1.2.0, and while trying to upload a mp4 video file, got this error. 
This is with **upload** method.
<pre>
java.lang.RuntimeException: Invalid image file
at com.cloudinary.android.UploaderStrategy.callApi(UploaderStrategy.java:104)
at com.cloudinary.Uploader.callApi(Uploader.java:22)
at com.cloudinary.Uploader.upload(Uploader.java:55)
</pre>

<pre>
Cloudinary cloudinary = new Cloudinary(ObjectUtils.asMap(
                "cloud_name", "XXXX",
                "api_key", "XXXX",
                "api_secret", "XXXX"));

File toUpload = new File("path to file.mp4");
uploadResult = cloudinary.uploader().upload(toUpload, options);
remoteUrl = uploadResult.get("url").toString();
</pre>

Also, I get the same error, when I try to upload some random files like mp3, or xls. PDF works though, with this same code, after which I thought I should try with the **upload** method.

With **uploadLargeRaw**, it works now for videos. But, the returned url doesn't have the file extension. And, also, there is no preview image. Is there a way that I can upload a video, and also get a generated preview of the same, as it is done for PDF files?

**Comment by tocker** [comment]
What values did you pass in the `options` variable?
Please make sure to you include the following value:

```java
options.put("resource_type", "video");
```

As for the returned url, it doesn't require an extension - it works as is. However if you wish to specify the format, you can add an extension ('`mp4`', '`ogv`', or '`webm`') and the video will convert to that format. Adding an image extension '`jpg`' or '`png`' will return an image ("thumbnail") of the video. Adding '`gif`' to the url will produce an animated GIF from the movie.

To checkout more options, see the [Video management documentation](http://cloudinary.com/documentation/video_management).

**Comment by coomar2841** [comment]
@tocker Thanks for you response. This works, after I followed the new announcement on the website, and tried it out. I will close this issue now.

**Comment by grath92** [comment]
File file = new File(filePath);
 JSONObject cloudinaryResult = new JSONObject(cloudinary.uploader().upload(file, ObjectUtils.asMap("resource_type", "image")));

System.err:     at com.cloudinary.android.UploaderStrategy.callApi(UploaderStrategy.java:50)
04-11 19:03:48.920 18295-18295/com.gkr.locationfeatcher W/System.err:     at com.cloudinary.Uploader.callApi(Uploader.java:22)
04-11 19:03:48.920 18295-18295/com.gkr.locationfeatcher W/System.err:     at com.cloudinary.Uploader.upload

Image not upload in Android 
Plsss help..
Thanks..

**Comment by lby1992** [comment]
@tocker thanks for your answer
