### ISSUE TITLE
Opacity transformation doesn't support nulls

### ISSUE THREAD

**Issue by IddoAlex** [cloudinary/cloudinary_java#206]
Hi,
It seems like all non-number parameters are nullable, and will get filtered during the generate() method.
Why not change opacity from int to an Integer, and allow it to behave the same?
Otherwise, users need to perform a null check when not using the primitive, which ruins the flow of the builder.

Thanks!

**Comment by aditimadan-Cloudinary** [comment]
Hi,
I have opened a request on your behalf to the SDK team but if you would like to raise a pull request you are more than welcome and it will be much quicker via the pull request.

Thanks,
Aditi

**Comment by aditimadan-Cloudinary** [comment]
@IddoAlex This issue has been fixed
