### ISSUE TITLE
How to use Upload functionality in Java in Playfarmework ?

### ISSUE THREAD

**Issue by ankit-iiita2006** [cloudinary/cloudinary_java#22]
As per the Java Image upload doc. This should work for uploading images:-
import com.cloudinary.Cloudinary;
Cloudinary cloudinary = new Cloudinary();
cloudinary.upload(fileRef, ObjectUtils.emptyMap());

However I am not able to find any ObjectUtils class in com.cloudinary.\* packages.

I am using following sbt dependnecy 
   "com.cloudinary" % "cloudinary" % "1.0.14"

Can someone please let me know, how I can fix it ?

Thanks,
Ankit

**Comment by tocker** [comment]
Hi @ankitmobolt ,

ObjectUtils was introduced in version 1.1.0. Current version is 1.2.0.
You will need to update your dependency to use it.

It updating is absolutely not possible, try using `Cloudinary.emptyMap()`.

Hope this helps :smile: 

@tocker

**Comment by ReaktorDTR** [comment]
Ahhh, show me please Cloudinary.emptyMap() method in sources. I can't find any method with this signature, but ObjectUtils.emptyMap() used in whole code.
