### ISSUE TITLE
Must supply API KEY when doing unsigned upload

### ISSUE THREAD

**Issue by AgonLohaj** [cloudinary/cloudinary_java#23]
The UploaderStrategy is requiring for an api key even though I'm doing unsigned upload:
String apiKey = ObjectUtils.asString(options.get("api_key"), this.cloudinary().config.apiKey);
if (apiKey == null)
	throw new IllegalArgumentException("Must supply api_key");

**Comment by TalLevAmi** [comment]
The api_key should be given even if an unsigned upload preset is used. The api_secret is not needed as the signature is skipped.

**Comment by AgonLohaj** [comment]
I was just reading this blog, and also in iOS it works without api_key:
Quote: "Now, in order to perform unsigned upload, simply call Cloudinary's upload API while setting the upload_preset parameter to the unique name. No need to set the API Key and Secret credentials of your account.". From here: http://cloudinary.com/blog/direct_upload_made_easy_from_browser_or_mobile_app_to_the_cloud

**Comment by TalLevAmi** [comment]
You are right. Sorry for the confusion. We'll fix this.

**Comment by TalLevAmi** [comment]
Solved by e7f247ad0ce689cf3fc52c8ccfe250c7ad8f424d

**Comment by AgonLohaj** [comment]
Nice, thank you.
