### ISSUE TITLE
Cloudinary.emptyMap()

### ISSUE THREAD

**Issue by benmarten** [cloudinary/cloudinary_java#24]
Cloudinary.emptyMap() should be ObjectUtils.emptyMap()

**Comment by taragano** [comment]
Thank you for reporting about it.
We've updated the readme file accordingly.

**Comment by RahulSDeshpande** [comment]
Thank you @benmarten..

Hi @taragano..

Sorry but I could not find the corrected README.
Its still says ```Cloudinary.emptyMap()```

Thank you.

**Comment by itaibenari** [comment]
@RahulSDeshpande 
The Android README was corrected. Hopefully that's the one you meant. Please reopen if not.
