### ISSUE TITLE
phash treatment mismatch between iOS and Android SDKs

### ISSUE THREAD

**Issue by martin-gearzero** [cloudinary/cloudinary_java#27]
We are using the "Safe mobile uploading" methods on Android and iOS as documented here, respectively:

https://github.com/cloudinary/cloudinary_java/tree/master/cloudinary-android#safe-mobile-uploading
https://github.com/cloudinary/cloudinary_ios#safe-mobile-uploading

Server-side, we use the scala library to create the signature string which looks something like this:

"notification_url=https://myserver.com/photo/notify&phash=1&timestamp=1437155198"

Notice that the value for "phash" is "1".

Using version 1.2.1 of the Android library, I am seeing a 401 error:

{
    "error": {
        "message": "Invalid Signature 25ed8e31b995bb927966616df2a42b979a2717f0. String to sign - 'notification_url=https://myserver.com/photo/notify&phash=true&timestamp=1437155198'."
    }
}

Notice that the value for "phash" is "true", which is the root cause of the invalid signature.

Util.buildUploadParams() uses the Boolean.toString() value of phash to generate the signature string, which is either "true" or "false". We could change the server to use "true" instead of "1" and fix Android, however this will break the iOS implementation:

[CLUploader buildUploadParams] turns phash into an NSNumber whose stringValue is "1" or "0", not "true" or "false".

https://github.com/cloudinary/cloudinary_ios/blob/master/Cloudinary/CLUploader.m

This mismatch necessitates a branch on the server or subclassing the Uploader or CLUploader class on one of the clients to override buildUploadParams, both of which are hacky.

Please consider backwards compatibility when fixing this issue, otherwise it could break existing implementations.

Thanks!

**Comment by taragano** [comment]
Our system was recently updated to accept either `1` or `true`. Can you please retry it and let us know if it works for you now?

**Comment by martin-gearzero** [comment]
Yes, this seems to be working now without needing to subclass Uploader. Thanks!
