### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Qnalo** [cloudinary/cloudinary_java#29]
Hi,
    We downloaded the files and try to use as per instruction.
There is compilation error .Below code is mentioned in this page.

http://cloudinary.com/documentation/java_integration

There is compilation error in it.

import java.io.File;

import java.util.Map;

...

File toUpload = new File("daisy.png");

Map uploadResult = cloudinary.uploader().upload(toUpload);

We corrected the compilation error by using this code.

But it is still not working.

Map config = ObjectUtils.asMap(
  "cloud_name", "my_cloud_name",
  "api_key", "my_api_key",
  "api_secret", "my_api_secret");
Cloudinary cloudinary = new Cloudinary(config);
Map result = cloudinary.api().resource("sample", ObjectUtils.emptyMap());

**Comment by Qnalo** [comment]
hi,
    I am using Jdk 1.6

**Comment by itaibenari** [comment]
@Qnalo please share the compilation error you're getting. Also, what exactly do you mean by "not working"? It looks as though the 2 code snippets you shared are not meant to do the same thing. One is supposed to upload a resource and the other requests info on an existing resource.

**Comment by Qnalo** [comment]
Compilation Error comes in this line:
//error

	Map uploadResult = cloudinary.uploader().upload(toUpload);

We need to pass extra parameter i.e. a object of Map to remove error.
//correct

Map uploadResult = cloudinary.uploader().upload(toUpload,params);

Not working means:
It is not uploading the image to the cloudinary account.

This code snippet is mentioned in the document and not working.

**Comment by Qnalo** [comment]
Hi Any update on this.

**Comment by taragano** [comment]
We'll fix our documentation. In the meantime, can you please share an accurate UTC time of an upload attempt and cloud name used so we'll be able to have a deeper look at it in our logs?

**Comment by Qnalo** [comment]
I don't have the UTC time.Is it fine to display cloud name publicly.

Is it working on your side.

**Comment by Qnalo** [comment]
Hi
    We are using only cloudinary-core java files.

Regards

**Comment by Qnalo** [comment]
Do you a simple jar file to start with instead of so much files.
We do not use maven.
We didn't use other files like http42,http44 we just copy the source file
from core java files into our projects.
Can this be the reason that it is not working.
Can you provide single jar file to start.

**Comment by wagaun** [comment]
You will need the following jars:

+- com.cloudinary:cloudinary-http42:jar:1.2.1:compile

+- org.apache.commons:commons-lang3:jar:3.1:compile

\- org.apache.httpcomponents:httpmime:jar:4.2.1:compile

I suggest you to download the jar files and uncompress them in your
classpath.

That should work.

On Wed, Sep 23, 2015 at 12:24 PM, Qnalo <notifications@github.com> wrote:

> Do you a simple jar file to start with instead of so much files.
> We do not use maven.
> We didn't use other files like http42,http44 we just copy the source file
> from core java files into our projects.
> Can this be the reason that it is not working.
> Can you provide single jar file to start.
>
>
> On Wed, Sep 23, 2015 at 8:20 AM, Qnalo OnlineStore <qnalosales@gmail.com>
> wrote:
>
> > Hi
> > We are using only cloudinary-core java files.
> >
> > Regards
> >
> > On Wed, Sep 23, 2015 at 12:06 AM, Itay Taragano <
> notifications@github.com>
> > wrote:
> >
> >> We'll fix our documentation. In the meantime, can you please share an
> >> accurate UTC time of an upload attempt and cloud name used so we'll be
> able
> >> to have a deeper look at it in our logs?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/cloudinary/cloudinary_java/issues/29#issuecomment-142377093
> >
> >> .
>
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudinary/cloudinary_java/issues/29#issuecomment-142479952>
> .
>



-- 
Wagner Tsuchiya

**Comment by Qnalo** [comment]
Hi,
    from where can i download cloudinary-http42:jar file.

Regards

**Comment by TalLevAmi** [comment]
See https://github.com/cloudinary/cloudinary_java#setup : 
https://repo1.maven.org/maven2/com/cloudinary/cloudinary-core/1.2.1/cloudinary-core-1.2.1.jar
https://repo1.maven.org/maven2/com/cloudinary/cloudinary-http44/1.2.1/cloudinary-http44-1.2.1.jar

if you need the previous version of httpclient (http42):
https://repo1.maven.org/maven2/com/cloudinary/cloudinary-http42/1.2.1/cloudinary-http42-1.2.1.jar

**Comment by Qnalo** [comment]
It is not working after initialization.
Map config = com.cloudinary.utils.ObjectUtils.asMap(
								  "cloud_name", "####uisaj",
								  "api_key", "####",
								  "api_secret", "######-k6#####");
						System.out.println(config.size());
						Cloudinary cloudinary = new Cloudinary(config);
						System.out.println("------>"+cloudinary.randomPublicId());

**Comment by dudadayan** [comment]
add this to proguard-rules:

-keep class com.cloudinary.** { *; }

**Comment by idobarnoam** [comment]
@Qnalo are you still experiencing this issue?

**Comment by idobarnoam** [comment]
Hi 
We apologize for the very delayed response.

As it probably not relevant anymore, we’re closing this issue.

Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket, if our assistance is still needed.
