### ISSUE TITLE
The `max_results` option is missed for the `Api.resourcesByIds` method

### ISSUE THREAD

**Issue by gtors** [cloudinary/cloudinary_java#31]
The [resourcesByIds](https://github.com/cloudinary/cloudinary_java/blob/cloudinary-parent-1.2.1/cloudinary-core/src/main/java/com/cloudinary/Api.java#L81) should support this option.

**Comment by itaibenari** [comment]
@gtors the reason `max_results` is not an option is because you actually provide a list of ids which implies you control the number of results you want to get back. Is your use case somehow different?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
