### ISSUE TITLE
generating the signature with API 

### ISSUE THREAD

**Issue by pixelbendr** [cloudinary/cloudinary_java#32]
Can the signature be generated with your API?

**Comment by TalLevAmi** [comment]
You can use [cloudinary.signRequest] (https://github.com/cloudinary/cloudinary_java/blob/018574c13f4512211f40b34ce0c5e018b9ff6544/cloudinary-core/src/main/java/com/cloudinary/Cloudinary.java#L155) for generating the signature and adding the api_key to the request.

**Comment by pixelbendr** [comment]
Can this be done by using a service like Parse.com?

**Comment by TalLevAmi** [comment]
Yes, see https://github.com/cloudinary/cloudinary_parse

**Comment by pixelbendr** [comment]
Thanks.

**Comment by pixelbendr** [comment]
My use case is like this. Please if you can offer any help or adjustments.

1. User tries to upload image from iOS or Android app.
2. An API request is made to parse.com to retrieve signature.
3. The file is uploaded to Cloudinary using iOS or Android SDK.
4. After successful upload image url is returned to client to be stored on server.

**Comment by TalLevAmi** [comment]
The should give you the most control. Another alternative is to use unsigned uploads, see http://cloudinary.com/blog/direct_upload_made_easy_from_browser_or_mobile_app_to_the_cloud

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
