### ISSUE TITLE
Nothing is working.

### ISSUE THREAD

**Issue by Qnalo** [cloudinary/cloudinary_java#33]
Hi,
We downloaded the files and try to use as per instruction.
There is compilation error .Below code is mentioned in this page.

http://cloudinary.com/documentation/java_integration

There is compilation error in it.

import java.io.File;

import java.util.Map;

...

File toUpload = new File("daisy.png");

Map uploadResult = cloudinary.uploader().upload(toUpload);

We corrected the compilation error by using this code.

But it is still not working.

Map config = ObjectUtils.asMap(
"cloud_name", "my_cloud_name",
"api_key", "my_api_key",
"api_secret", "my_api_secret");
Cloudinary cloudinary = new Cloudinary(config);
Map result = cloudinary.api().resource("sample", ObjectUtils.emptyMap());

**Comment by TalLevAmi** [comment]
@Qnalo What is the error you are getting?

**Comment by Qnalo** [comment]
No error display but image is not getting uploaded into the cloud.
You can also try uploading the image.

**Comment by Qnalo** [comment]
It is not working after initialization.
Map config = com.cloudinary.utils.ObjectUtils.asMap(
"cloud_name", "####uisaj",
"api_key", "####",
"api_secret", "######-k6#####");
System.out.println(config.size());
Cloudinary cloudinary = new Cloudinary(config);
System.out.println("------>"+cloudinary.randomPublicId());

**Comment by taragano** [comment]
Hi @Qnalo,
I see your last response from quite a time ago. I just wanted to check whether you still experience the same (or any other) issue?

**Comment by taragano** [comment]
@Qnalo - Do you still experience this issue?
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks
