### ISSUE TITLE
Hide constructors of utility classes

### ISSUE THREAD

**Issue by vil02** [cloudinary/cloudinary_java#340]
## Bug report for Cloudinary Java SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
These classes:
- [`ApiUtils`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-http5/src/main/java/com/cloudinary/http5/ApiUtils.java),
- [`SmartUrlEncoder`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/SmartUrlEncoder.java),
- [`Util`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/Util.java),
- [`HtmlEscape`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/utils/HtmlEscape.java),
- [`StringUtils`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/utils/StringUtils.java),
- [`ObjectUtils`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/utils/ObjectUtils.java),
- [`Base64Map`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/utils/Base64Map.java),
- [`Feature`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-test-common/src/main/java/com/cloudinary/test/helpers/Feature.java),
- [`MetadataTestHelper`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-test-common/src/main/java/com/cloudinary/test/MetadataTestHelper.java),
- [`Singleton`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-taglib/src/main/java/com/cloudinary/Singleton.java),

are _utilities_ and their constructors should be hidden and they should be marked as `final`. Such change makes it harder to misuse them (prevents instantiation and inheritance) and makes the coverage reports more accurate.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[x] Other (Specify) - code quality

Related to #337.

**Comment by s-vamshi** [comment]
Hey @vil02 , i would like to work on this issue can you please assign this to me?

**Comment by vil02** [comment]
Hi @s-vamshi,

I am not a maintainer of this repository. I by creating this issue I explicitly expressed my interest in being assigned to it. Please have a look at: [**DO NOT submit a PR without an active Issue that has been approved.**](https://cloudinary.com/blog/hacktoberfest-open-source-celebration-cloudinary#what_are_the_rules_).

@colbyfayock, @adimiz1, @const-cloudinary: could you please have a look?

**Comment by vil02** [comment]
So... could I create a pull request fixing this?

**Comment by michal-sordyl-cloudinary** [comment]
@vil02 yes, please create PR

**Comment by RaghavMangla** [comment]
Hi! which among these issues, are hacktoberfest accepted
