### ISSUE TITLE
Question: how to run tests?

### ISSUE THREAD

**Issue by nitram509** [cloudinary/cloudinary_java#342]
I have a simple question: how do I run tests?

I did a checkout of the source, and build and test, but the tests to complain: `IllegalArgumentException: Invalid CLOUDINARY_URL scheme. Expecting to start with 'cloudinary://'`

In my naive understanding, I should be able to checkout this sources and being able to run the tests, with the provided `gradlew`, yes?

I did this:
```shell
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export CLOUDINARY_URL="cloudinary://123456789012345:abcdeghijklmnopqrstuvwxyz12@n07t21i7"

java -version
> OpenJDK 64-Bit Server VM Corretto-8.362.08.1 (build 25.362-b08, mixed mode)

./gradlew build test
> com.cloudinary.test.ApiTest > classMethod FAILED
>    java.lang.IllegalArgumentException: Invalid CLOUDINARY_URL scheme. Expecting to start with 'cloudinary://'
> 
> 46 tests completed, 14 failed, 32 skipped
> 
> [...]
> Execution failed for task ':cloudinary-http5:test'.
> [...]
```

**Comment by adimiz1** [comment]
To run the tests you need your Cloudinary credentials, API key, secret and Cloud name
./gradlew clean test -DCLOUDINARY_URL=cloudinary://<api_key>:<api_secret>@<cloud_name>
I'm closing the issue, feel free to re-open if you need further assistance
