### ISSUE TITLE
Bug: documentation wrongly states Java 6

### ISSUE THREAD

**Issue by nitram509** [cloudinary/cloudinary_java#344]
## Bug report for Cloudinary Java SDK

The documentation on https://cloudinary.com/documentation/java_integration
states that (cite) "The library is built for Java 6...." but actually, in the `java_shared.gradle` file
there is `sourceCompatibility = 1.8` specified.

Which means, the documentation should be updated.

**Comment by ManishS6** [comment]
Hi @nitram509 , I would like to work on this. 
Please assign.

**Comment by nitram509** [comment]
@ManishS6 I'm not a maintainer ... just reporting issues here as well and also would like to work on it ;)

**Comment by michal-sordyl-cloudinary** [comment]
@nitram509 Thank you for reporting the issue. We will update documentation.

**Comment by jackieros** [comment]
@nitram509 - Just updating that the [Java SDK guide](https://cloudinary.com/documentation/java_integration) in the Cloudinary docs has been updated for SDK v2 (a variety of updates throughout the guide, including the version issue you raised above).  Thanks again for raising it!
