### ISSUE TITLE
Large image upload

### ISSUE THREAD

**Issue by VihaanVerma89** [cloudinary/cloudinary_java#35]
Hey, Is there any image compression functionality provided to compress large camera images locally before uploading them ?

**Comment by horsejockey** [comment]
Yes, please let me know if this gets implemented.

**Comment by yakirp** [comment]
Hi @VihaanVerma89 , @horsejockey 

We are now supporting Preprocess image uploads. 
Please refer to our [blog](https://cloudinary.com/blog/giving_your_mobile_app_a_boost_part_1_pre_upload_image_processing) and [documentation](https://cloudinary.com/documentation/android_image_and_video_upload#preprocess_image_uploads) for more information about that.

Best,
Yakir
