### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [cloudinary/cloudinary_java#37]
Warning:Conflict with dependency 'org.hamcrest:hamcrest-core'. Resolved versions for app (1.1) and test app (1.3) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'junit:junit'. Resolved versions for app (4.10) and test app (4.12) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by adimiz1** [comment]
This issue was fixed a while ago but was not closed.
