### ISSUE TITLE
Support for non blocking and/or stream based image transfer

### ISSUE THREAD

**Issue by tanneess** [cloudinary/cloudinary_java#38]
Hi,

As I read the code of the http44 connector I see that all  methods of tranfer require for the file to be entirely on my server (being in memory or on the hard drive) before it can be sent to the cloudinary server. This is really a pitty because my server is only an intermediary, a gatekeeper. No need for it to ever store/have/hold then entire file in memory or HD. 
Also non blocking support would allow for better handling of load. Now each file upload requires a thread which (given the size of the files) could be monopolized for a long time. 

Could there not be a non-blocking and/or stream based implementation for cloudinary java API?

**Comment by rocketraman** [comment]
+1 for this. It should be pretty easy to add stream-based upload just by checking the type of the File parameter matches `InputStream` here:

https://github.com/cloudinary/cloudinary_java/blob/master/cloudinary-http44/src/main/java/com/cloudinary/http44/UploaderStrategy.java#L103

and then using the `addBinaryBody` method that takes an `InputStream` as an argument:

https://hc.apache.org/httpcomponents-client-ga/httpmime/apidocs/org/apache/http/entity/mime/MultipartEntityBuilder.html

If versions earlier than http client 4.4 also support that, the same change should be applied there.

Agreed also on non-blocking, but I think that should probably be a separate issue.

**Comment by idobarnoam** [comment]
Hi @tanneess ,

We apologize for the very delayed response.
Just wanted to let you know that this is supported by the "MediaManager.upload" method.

As it probably not relevant anymore, we’re closing this issue.
Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket, if our assistance is still needed.
