### ISSUE TITLE
Upload not working on android with version 1.2.2

### ISSUE THREAD

**Issue by WanClem** [cloudinary/cloudinary_java#39]
This is what I have tried so for,

                  ` Cloudinary cloudinary = new Cloudinary();

                   Map<String, String> config = new HashMap<>();

                   config.put("cloud_name", "blabla");

                   config.put("api_key", "blabla");

                   config.put("api_secret", "blabla");

                   Map callbacks = cloudinary.uploader().upload(inputStream, ObjectUtils.emptyMap());

                     if (callbacks != null && !callbacks.isEmpty()) {

                                String callbackUrl = (String) callbacks.get("public_id");

                                 String callbackUrlToBeSaved = cloudinary.url().generate(callbackUrl);

                      }`

I get no callback url at all;
By the way I got the library via gradle in android studio with this dependency 

`compile 'com.cloudinary:cloudinary-android:1.2.2' `      and not through the individual .jar files.

Am I doing anything wrong? Please help.Thanks

**Comment by taragano** [comment]
Please share some more of your code's context. Specifically:

1. How is `inputStream` in your code created?
2. What is the value returned by upload? Note that it could be an error message.
3. If you do get a response from Cloudinary (either a success or an error), please share some more information regarding the request, and the timestamp of the upload, so we'll be able to take a look in our logs. We can continue this on our support ticket if it's more convenient for you.

**Comment by WanClem** [comment]
Ok,more codes of how I get the inputstream from android is below

    `public class MainActivity extends AppCompatActivity implements OnClickListener{
                /**
                * Request code sent to pick an image from gallery
                **/
               private static final int REQUEST_CODE_GALLERY = 0x1;

               protected void onCreate(Bundle savedInstanceState){
               super.onCreate(savedInstanceState);

               Button uploadPhotoButton = (Button)findViewById(R.id.upload_profile_photo);
               uploadPhotoButton.setOnClickListener(this):

                }
       
               @Override
               public void onClick(View v)
                {
                  //When upload photo button is clicked open gallery to pick a photo for upload
                   if(v.getId()==R.id.upload_profile_photo)
                    {
                           //Open Gallery method is defined below
                           openGallery("Pick profile photo to upload");
                        }
                  }
             
               public void openGallery(String title) {
               Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
               photoPickerIntent.setType("image/*");
               Intent mChooser = Intent.createChooser(photoPickerIntent, title);
              startActivityForResult(mChooser, REQUEST_CODE_GALLERY);
               }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case REQUEST_CODE_GALLERY:
                try {
                    InputStream inputStream = getContentResolver().openInputStream(data.getData());
                    uploadPhoto(inputStream, photoViewType);
                    if (inputStream != null) {
                        inputStream.close();
                    }
                } catch (Exception ignored) {
                }
        }
    }

              public void uploadPhoto(final InputStream inputStream, final String photoType) {
                runOnUiThread(new Runnable() {
                  @Override
                  public void run() {

                displayablePhotoFlipper.setDisplayedChild(0);
                progressDialog.setMessage("Uploading Photo");
                progressDialog.show();

                Cloudinary cloudinary = AppUtils.getCloudinary();
                try {
                    Map callbacks = cloudinary.uploader().upload(inputStream, ObjectUtils.emptyMap());
                    if (callbacks != null && !callbacks.isEmpty()) {
                        String callbackUrl = (String) callbacks.get("public_id");
                        String callbackUrlToBeStored = cloudinary.url().generate(callbackUrl);
                        displayablePhotoFlipper.setDisplayedChild(1);
                           Glide.with(MainActivity.this).load(callbackUrlToBeStored).into(displayablePhoto);
                        if (progressDialog.isShowing()) {
                            progressDialog.dismiss();
                        }
                         Toast.make(MainActivity.this,"Photo Upload Complete",Toast.LENGTH_LONG).show();
                    }

                } catch (IOException e) {
                    progressDialog.dismiss();
                    Toast.makeText(CurrentUserDisplayablePhotoActivity.this, e.getMessage(), Toast.LENGTH_LONG).show();
                }
            }
        });
    }
}`

 //The dialog never gets dismissed and no call back returned.What am i doing wrong.Thanks for your response.

**Comment by grath92** [comment]
Hi,
HashMap config = new HashMap();
config.put("cloud_name", "****");
config.put("api_key", "*************");
config.put("api_secret", "******************");
Cloudinary cloudinary = new Cloudinary(config);
Case-1:
JSONObject cloudinaryResult = new JSONObject(cloudinary.uploader().upload(filePath, ObjectUtils.emptyMap()));
Case-2:
JSONObject cloudinaryResult = new JSONObject(cloudinary.uploader().unsignedUpload(filePath,"mgksra",ObjectUtils.emptyMap()));
I have done both above cases, but not working.
Even It not showing any error.
Plssss help....
Thanks

**Comment by taragano** [comment]
Hi @WanClem, @grath92,

I'm very sorry for our response delay. As it's been a while, I just wanted to ask whether you still experience this issue and need further assistance?

**Comment by grath92** [comment]
Hi Itay,

It's fine.I am solve that issue.

Thanks
Gopal

**Comment by taragano** [comment]
Thank you @grath92.
I'll be Closing this issue due to the time elapsed. @WanClem, please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
