### ISSUE TITLE
Resume Upload & Upload callback

### ISSUE THREAD

**Issue by cprakashagr** [cloudinary/cloudinary_java#40]
Hi,

I was performing Video upload via Signed Upload Strategy from my Android device. While I was trying all these stuff. I accidentally turned off my WiFi and the upload was failed. So, it would be great if we have a resume upload use case handled. Because every time its fail, I have to re trigger upload with new tokens. If this use case is already handled, please let me know the method name. I couldn't find any.

Moreover, I could not find API for upload callback. Its very hard / tidy watching the progress view rolling without letting the user know the progress report. Any help would be appreciable.

Thanks,
CP.

**Comment by idobarnoam** [comment]
Hi @cprakashagr,

We apologize for the very delayed response. 
Just wanted to let you know that this is supported with the "MediaManager.upload" method.

As it probably not relevant anymore, we’re closing this issue. 
Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket, if our assistance is still needed.
