### ISSUE TITLE
Uploader#upload is missing http/url upload option.

### ISSUE THREAD

**Issue by zafrani** [cloudinary/cloudinary_java#45]
The docs http://cloudinary.com/documentation/java_integration mention being able to pass a String for a photo's http location:

![screen shot 2016-05-14 at 1 02 23 am](https://cloud.githubusercontent.com/assets/4250407/15267187/8fff6e50-196f-11e6-9273-a47dcd4a05d9.png)

However I'm not finding any upload method with a single String parameter option. 

```
    <dependency>
        <groupId>com.cloudinary</groupId>
        <artifactId>cloudinary-http44</artifactId>
        <version>1.4.1</version>
    </dependency>
```

**Comment by MaorGar** [comment]
Hi @zafrani,

You are right. The upload method requires options parameters. You can pass an empty map (`ObjectUtils.emptyMap()`)  if you don't have any upload specifications. 

You can find more information about upload methods [here](http://cloudinary.com/documentation/java_image_upload#data_uploading_options).

Good luck :)

**Comment by MaorGariv** [comment]
Hi,

Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
