### ISSUE TITLE
Combine multiple Effects

### ISSUE THREAD

**Issue by YourDirtyMum** [cloudinary/cloudinary_java#47]
I'm trying to upload an image with 2 effects. I've tried multiple approaches but cannot get it work.

new Transformation().effect("blur:500").crop("scale").width(100).height(40).effect("blue:50")

How can I combine these 2 effects, or how can i add multiple Transformations into the upload of 1 picture.

What am I missing here?
Thank you for help!

**Comment by YourDirtyMum** [comment]
Ok, got it.
Just found out about the ".chain()" method.

**Comment by Allsimon** [comment]
Hi,

Can you please explain how did you manage to chain these transformation ?
`.chain()` method just clear all previously used params or am I missing  something ?
```
Map uploadResult = cloudinary.uploader().upload(image, ObjectUtils.asMap(
        "transformation", Collections.singletonList(
                new Transformation().quality("auto").width(1500).height(1500).crop("lfill")
        )));
```
throws something about crop
```
Map uploadResult = cloudinary.uploader().upload(image, ObjectUtils.asMap(
        "transformation", Arrays.asList(
                new Transformation().quality("auto"),
                new Transformation().width(1500),
                new Transformation().height(1500),
                new Transformation().crop("lfill")
        )));
``` 
throws something about quality

**Comment by YourDirtyMum** [comment]
Hi,

I've used it this way:

`Transformation trans = new Transformation().crop("scale").width(100).height(40).effect("blur:500").chain().effect("blue:100");`

And then I added the transformations with the eager option:

` ObjectUtils.asMap(
                    "public_id", "publicid",
                    "eager", Arrays.asList(trans)));`
