### ISSUE TITLE
White background when using radius

### ISSUE THREAD

**Issue by nvhaiwork** [cloudinary/cloudinary_java#48]
http://res.cloudinary.com/cuffd/image/upload/w_1500,h_1000,r_90/sample.jpg

Please check this image, it has white background at conners.
Can I get transparent background image(guess cant coz it's jpg image)?
Can I set background color for the image(at conners)

**Comment by taragano** [comment]
The JPG format doesn't support transparency, therefore a default white background is applied.
The background color can be changed by setting the `background` parameter (`b` in URLs). e.g.,:
http://res.cloudinary.com/cuffd/image/upload/w_1500,h_1000,r_90,b_black/sample.jpg

You can tell Cloudinary to support it to a transparency-supported format and the corners would be transparent. For example, in PNG:
http://res.cloudinary.com/cuffd/image/upload/w_1500,h_1000,r_90/sample.png

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
