### ISSUE TITLE
How to get uploaded percentage to show user in cloudinary sdk

### ISSUE THREAD

**Issue by SureshKispotta** [cloudinary/cloudinary_java#49]

**Comment by MaorGariv** [comment]
Hi,
We currently don't support upload progress in Java.
We'll gladly update here as well when we introduce it.

**Comment by suyashgupta25** [comment]
Any Progress on this issue? 
We are really need this feature. 
You can see it here https://github.com/cloudinary/cloudinary_android/issues/6

**Comment by sunnytambi** [comment]
+1 to @suyashgupta25

**Comment by roeeba** [comment]
Version 1.11.0 was released on (please see - https://github.com/cloudinary/cloudinary_java/issues/72). It includes the progress callback. We'll be closing this issue now, but please feel free to re-open it if you see any issues.
