### ISSUE TITLE
Is the cloudinary API threadsafe?

### ISSUE THREAD

**Issue by malkusch** [cloudinary/cloudinary_java#50]
Can I reuse the Cloudinary instance between threads? If so, would you mind documenting that with e.g. a `@ThreadSafe` annotation?

Thank you very much

**Comment by MaorGariv** [comment]
Hi,

It is not ThreadSafe to reuse the instance.
Moreover, the [Admin API](http://cloudinary.com/documentation/admin_api) is not meant for high concurrency rates (2-3 max), while the Upload API can handle around 50.

**Comment by malkusch** [comment]
Thank you very much. This answers my question. You might consider adding that information to your documentation (unless I simply missed that part).

**Comment by malkusch** [comment]
Oh, and may I also ask, if threadsafety is also not available for the url building method `Cloudinary.url()`?

**Comment by MaorGariv** [comment]
Hi,
Thanks for your feedback. We are continuously working on further improving our docs and services.

The url building method doesn't affect the state, making it indeed threadsafe :)

Good luck.

**Comment by MaorGariv** [comment]
Hi,
We don't utilize the MultiThreadedHttpConnectionManager that enables the connection to be Threadsafe for our uploads.

**Comment by malkusch** [comment]
`MultiThreadedHttpConnectionManager` no longer exists in http-4. It became [`ThreadSafeClientConnManager`](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/tsccm/ThreadSafeClientConnManager.html) which was deprecated in favour of `PoolingClientConnectionManager`. When I debug the code I see indeed this `PoolingClientConnectionManager` is beeing used by the UploaderStrategy. More over the strategy uses a `CloseableHttpClient` which is explicitly thread safe.
