### ISSUE TITLE
Get Video Thumnails

### ISSUE THREAD

**Issue by toidv** [cloudinary/cloudinary_java#51]
How can I get video thumbnails from uploaded video, 
Currently, I called this api to get video thumbnails
```
String video = cloudinary.url().resourceType("video").imageTag(generateName(ProfileType.PROFILE_TYPE_VIDEO));
```

But it returns as below
```
<img src='http://res.cloudinary.com/toidv/video/upload/profile_438-video'/>
```

Please help to update document for this functionality! Thanks so much

**Comment by roeeba** [comment]
Hi @toidv, generating a video tag is done using the `videoTag` method (rather then `imageTag`). Please see - https://github.com/cloudinary/cloudinary_java/blob/master/cloudinary-core/src/test/java/com/cloudinary/test/CloudinaryTest.java#L725.

**Comment by toidv** [comment]
Thanks @roeeba for your quickly response. I get the result as below
```
<video poster='http://res.cloudinary.com/toidv/video/upload/profile_438-video.jpg'><source src='http://res.cloudinary.com/toidv/video/upload/profile_438-video.webm' type='video/webm'><source src='http://res.cloudinary.com/toidv/video/upload/profile_438-video.mp4' type='video/mp4'><source src='http://res.cloudinary.com/toidv/video/upload/profile_438-video.ogv' type='video/ogg'></video>
```
Actually, it is web format, do we have any way just return only url(http://res.cloudinary.com/chris-mackie/video/upload/profile_438-video.jpg)

**Comment by roeeba** [comment]
@toidv, to generate a URL (rather than an HTML tag) please remove the `videoTag` part of the `cloudinary.url()` method, like this:

`result = cloudinary.url().transformation(transformation).generate("test");`

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
