### ISSUE TITLE
Crash during upload

### ISSUE THREAD

**Issue by JulienArzul** [cloudinary/cloudinary_java#52]
Hello,

I'm using your SDK in an Android Application to upload videos to my Cloudinary folder. I've included Fabric in my application and a crash from your SDK has been reported.

Enclosed is the report downloaded on Crashlytics. The report only includes info of one phone but it appeared on all Android versions that I support (minsdk to 4.4) with different manufacturers.

The crash doesn't seem to happen a lot. It must be an edge case.

Thanks

[cloudinary_issue_29_crash_57eacabe012d00016963dc9b6b42e002.txt](https://github.com/cloudinary/cloudinary_java/files/498248/cloudinary_issue_29_crash_57eacabe012d00016963dc9b6b42e002.txt)

**Comment by taragano** [comment]
Hi @JulienArzul,

From what we could see, it seems that the crash is in AWS code. We couldn't find a cloudinary-related mentioning in there.
Can you please verify and let us know if there's any additional information you can share with us?

Thanks

**Comment by JulienArzul** [comment]
Wahou, I must have had my head elsewhere when I filed the bug... I'm uploading files with both AWS and Cloudinary and I got confused. Sorry about that !!

**Comment by taragano** [comment]
No worries :) 
Please let us know if there's anything else we can help you with.
