### ISSUE TITLE
Cloudinary image upload (Invalid signaure issue)

### ISSUE THREAD

**Issue by pingpingsim** [cloudinary/cloudinary_java#53]
I've been using the following code from the sample to upload images to Cloudinary and it has been working fine until one of the team member complains having issue uploading image using Android 5 device. Using simulator Android 5, I'm getting below runtime error. Please advise what could have done wrongly using below implementation.

java.lang.RuntimeException: Server returned unexpected status code - 401 - {"error":{"message":"Invalid Signature f11d48772281ea76f3fc49f25cb048ddef90a43d. String to sign - 'timestamp=1479686175'."}}

```
            Map config = new HashMap();
            config.put(KEY_CLOUD_NAME, BuildConfig.cloudinary_cloud_name);
            config.put(KEY_API_KEY, BuildConfig.cloudinary_api_key);
            config.put(KEY_API_SECRET, BuildConfig.cloudinary_api_secret);

            Cloudinary cloudinary = new Cloudinary(config);
            result = cloudinary.uploader().upload(fileToUpload, ObjectUtils.emptyMap());
```

**Comment by nadavofi** [comment]
Please follow the debug steps below:

1. Upgrade your SDK to the latest available.
2. Please check to make sure that "Automatic date and time" are enabled on your device as well as "Automatic time zone"?
3. Next, if the above didn't work, please try providing the `API_SECRET` and current `timestamp` (10 digits in UTC) within the upload-options Map and see if this fixes the bad-signature issue.

Let us know how it goes.

**Comment by nadavofi** [comment]
I'll be closing this issue due to time elapsed. Please feel free to contact us again if you encounter any further issues.

**Comment by IOsonoTAN** [comment]
Hi @nadavofi,

There is an example to generate a signature in Javascript?

I have already tried to hashing by sha1 but i don't get a result same as in document. (https://cloudinary.com/documentation/upload_images#creating_api_authentication_signatures)

**Comment by nadavofi** [comment]
**An important disclaimer:** Signature must be calculated on the server-side since this process involves **your api-secret which must be kept confidential.**
For demonstration purposes only(!), here's a quick JS snippet that shows how to calculate the signature based on a set of parameters which require signing: https://jsfiddle.net/nadavofi/3aqw8hoq/
