### ISSUE TITLE
Transformation().streamingProfile No method found

### ISSUE THREAD

**Issue by kumarlalapet** [cloudinary/cloudinary_java#56]
The following Cloudinary documentation instructs to use the streamingProfile method on the Transformation class. This method is not available.

http://cloudinary.com/documentation/video_manipulation_and_delivery#adaptive_bitrate_streaming_hls_and_mpeg_dash

```
cloudinary.uploader().upload("big_buck_bunny.mp4", 
        ObjectUtils.asMap("resource_type", "video",
        "eager", Arrays.asList(
              new Transformation().streamingProfile("full_hd").format("m3u8"),
            "eager_async", true,
            "eager_notification_url", "http://mysite/notify_endpoint"
            "public_id", "bb_bunny"));
```

Im using 1.6 version of the cloudinary android library. Please help.

**Comment by kumarlalapet** [comment]
The following code seems to work. Is this correct?

```
                    String format[] = { "streaming_profile", "full_hd", "format", "m3u8" };
                    Map results = dubsApp.getCloudinary().uploader().upload(videoFile,
                            ObjectUtils.asMap("resource_type", "video",
                                    "eager", Arrays.asList(new EagerTransformation().format("sp_hd/m3u8")),
                                    "eager_async", false,
                                    "public_id", "bb_bunny"));
```

**Comment by MaorGariv** [comment]
Hi,

Supporting `streamingProfile` is on our road-map.
As a workaround you can use the `rawTransformation` component - 

```
cloudinary.uploader().upload("http://res.cloudinary.com/demo/video/upload/dog.mp4",
                        ObjectUtils.asMap("resource_type", "video",
                                "eager", Arrays.asList(new EagerTransformation().format("m3u8").rawTransformation("sp_hd")),
                                "eager_async", true,
                                "public_id", "bb_bunny"));
```

(It's possible to change the Arrays.asList to a more optimised structure if using only 1 transformation)
I'll update here once `streamingProfile` is added.

**Comment by MaorGariv** [comment]
Hi,

Please note that [streamingProfile](https://github.com/cloudinary/cloudinary_java/blob/62a53416bc7611e97d9de4865e95abd826373c72/cloudinary-core/src/main/java/com/cloudinary/Transformation.java#L445) is already supported :)

Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
