### ISSUE TITLE
Runs upload on main thread?

### ISSUE THREAD

**Issue by silverAndroid** [cloudinary/cloudinary_java#58]
I'm having trouble using version 1.2.2 (the latest version shown on your README) when I try to upload an image, it throws a `android.os.NetworkOnMainThreadException`.

I wrote a [simple example](https://github.com/silverAndroid/cloudinary-upload-test) that throws this exception, which I tested on an LG V20 running Android 7.0 on the December security update.

**Comment by MaorGariv** [comment]
Hi,

The upload call requires server communication. Android usually doesn't allow it to happen on the main (UI) thread. 
You can try to wrap the upload call with an [AsyncTask](https://developer.android.com/reference/android/os/AsyncTask.html), for example. That way, the upload call takes place on a different thread.

**Comment by silverAndroid** [comment]
Shouldn't this be something the library handles?

**Comment by MaorGariv** [comment]
Usually this is something programmers would prefer to manage on their side rather than leaving it for 3rd party plugins to decide. 
That being said, we will consider adding such functionality in the future.

**Comment by alexgomes09** [comment]
When I call `uploader.upload` my assumption would be that it already handles the upload part for me on the background thread. (since I'm using android library) Why would it upload on the main thread anyway :confused:

**Comment by MaorGariv** [comment]
Hi @alexgomes09,

We are working on adding new functionalities and flows to our mobile SDKs, performing uploads from a different thread is one of the additions we're looking forward to implement:)

**Comment by silverAndroid** [comment]
Do you have a rough idea for when this will be implemented?

**Comment by MaorGariv** [comment]
Hi @silverAndroid,
There's still no ETA for it yet, but I'll gladly update here once it's ready and published.

**Comment by MaorGariv** [comment]
Hey,

This issue is now resolved with our new Android SDK:)

Closing this issue, please feel free to reach out again here or via a [support ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
