### ISSUE TITLE
How to delete folders via API?

### ISSUE THREAD

**Issue by rranke** [cloudinary/cloudinary_java#70]
In cloudinary-settings i have set "Auto-create folders" to "enabled".

When calling the method "deleteAllResources" via API, all images are going to be deleted, but empty folders are not deleted as well :(

But i also want to delete all the folders.

I tried: 
`cloudinary.api().deleteAllResources(ObjectUtils.emptyMap());`

**Comment by idobarnoam** [comment]
Hi Eric,

I see that my colleague Richard has answered this question in the support ticket you opened regarding your question.

In the reply, he points out that a direct call to the endpoint like the one below would delete the folder:

`curl -X DELETE -u <API_KEY>:<API_SECRET> "https://api.cloudinary.com/v1_1/<cloud_name>/folders/<folder>"`

I wanted to add that you could use our admin API to [list folders and subfolders](http://cloudinary.com/documentation/admin_api#manage_folders).
You could write a script that uses our admin API to list all the folders of your account, and then iterate them and perform a call to the endpoint with each one.

**Comment by rranke** [comment]
okay, if that is atm the only way, then ill try to use that. 
thanks!!
