### ISSUE TITLE
please release 1.10.0 to maven so that we can use ProgressCallback

### ISSUE THREAD

**Issue by KirtiCodeMaya** [cloudinary/cloudinary_java#72]
Hi, Please update the pom and release 1.10.0 for cloudinary-android so that we can use ProgressCallback while uploading image/video, otherwise let me know how can we use this feature.

FYI,
https://github.com/cloudinary/cloudinary_java/commit/f36b434bf3359fae9c450358a87f414f3f7fdfc7
This is not available in maven repos as mentioned here

Regards

**Comment by KirtiCodeMaya** [comment]
Do we have a ETA for when this version will be available on maven?

**Comment by roeeba** [comment]
Hi @KirtiCodeMaya, We're reviewing this request and will update soon.

**Comment by caixamagicasoftware** [comment]
Version 1.11 just got released!

**Comment by roeeba** [comment]
Hi guys, Version 1.11.0 was indeed released. It includes the progress callback. We'll be closing this issue now, but please feel free to re-open it if you see any issues.
