### ISSUE TITLE
Support for presigned urls

### ISSUE THREAD

**Issue by pulkitsinghal** [cloudinary/cloudinary_java#8]
The readme doesn't elaborate if support for presigned URLs exists in this project.

I think if it doesn't then it would be good to add it and if does exist then it would be good to expose it and if it is already exposed then it would be good to document it :)

Sidenote: Someone suggested that since presigned URLs have an expiration time, they are useful when it comes to protecting my account bandwidth against a client with an image URL and a while loop!!! This sounds like a decent idea but I have reservations because I'm not sure what stops a client who received a presigned image URL from me ... From calling a PUT on that URL and changing the content? I don't see any granular differentiation for GET vs PUT/Post/Delete ... Am I missing something?

**Comment by tocker** [comment]
Closing due to the elapsed time :clock1:  . If you still have questions, please contact our support or open a new ticket.
