### ISSUE TITLE
Plans for a JSF taglib?

### ISSUE THREAD

**Issue by djmj** [cloudinary/cloudinary_java#87]
We are using the JSP successor JSF. Do you have a taglib for JSF?

JSF is the new industry standard in Java EE framework and out since 2004, so maybe you should also support it, which is good sales argument. 

Porting your JSP tags to JSF should not be that complex.

**Comment by roeeba** [comment]
Hi @djmj, thank you for your suggestion. This is currently not in our plans for the near future. If you end up implementing this yourself, we encourage our users to offer their pull requests.

**Comment by djmj** [comment]
Hi @roeeba, we evaluate cloudinary because we currently will not have time for that, especially if we pay for the service. This also seems like more of a scalable sales feature for your sales department which should be a good investment. JSP is for legacy applications and JSF for future.

We could use a simple jsf bean with some methods to retrieve the cloudinary-url for an image using your SDK, but of cause is not so nice and flexible as a real component.

**Comment by roeeba** [comment]
Hi @djmj, thank you for the feedback. I've shared your inputs with our product team. We'll make sure to update here on any progress done in this matter.

**Comment by roeeba** [comment]
Closing this issue. As mentioned, this is not currently in our short/mid plans. We will update here on any status change. 
Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
