### ISSUE TITLE
fetch all images and fetching a single image without using file name

### ISSUE THREAD

**Issue by lavanarul** [cloudinary/cloudinary_java#89]
Hi....I want to display all images in a gridview as thumbnail by folder wise.after i click on thumbnail i need to show orginal size of that image.how can i do that...i seen many example which are used file name and also it fetch a single image only.pls any one guide me.Thanks in advance

**Comment by MaorGariv** [comment]
Hi @lavanarul 

You can use the [Admin API](http://cloudinary.com/documentation/admin_api#list_resources) to list your Account's resources. The response also returns the original file size.
Then, after getting the `public_id`, generate the URL with on-the-fly transformations to the desired thumbnail size.

**Comment by MaorGariv** [comment]
Hi @lavanarul,

Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
