### ISSUE TITLE
Upload photo on Android device with wrong time

### ISSUE THREAD

**Issue by y-polek** [cloudinary/cloudinary_java#95]
One of my users has wrong time settings on his Android device (and he doesn't want to change them).
Because of this, requests on his device finishes with "Stale request" error.
Is it possible to bypass this problem somehow and get Cloudinary to work on devices with wrong time?

**Comment by yakirp** [comment]
Hi,
While using signed upload with Cloudinary Android SDK, the signature method must use the current device timestamp.

**To overcame your issue you have 2 options:**

1. [Unsigned upload](http://cloudinary.com/blog/direct_upload_made_easy_from_browser_or_mobile_app_to_the_cloud) - This method allows uploading directly from your Android application to Cloudinary with no predefined authentication (So there is no need for timestamp). Please note that you will need to specify a preset in your Cloudinary admin panel to handle these uploads.

 2. Generating the HTTP/S request and the signature by yourself - [Manually generate the signature](https://support.cloudinary.com/hc/en-us/articles/203817991-How-to-generate-a-Cloudinary-signature-on-my-own-) at your server (This helps to keep your api_secret safe) and upload the image with [Cloudinary RESTful API](http://cloudinary.com/documentation/upload_images#uploading_with_a_direct_call_to_the_api) from your Android application.  

Please let me know if you need any further assistance with this

**Comment by yakirp** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
